# Generated by Django 3.0 on 2021-03-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisewithdraw',
            name='payment_method',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
