# Generated by Django 3.0 on 2021-03-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_franchisewithdraw_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_requests',
            name='payment_address',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw_requests',
            name='payment_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw_requests',
            name='payment_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw_requests',
            name='payment_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
