# Generated by Django 3.0 on 2021-03-06 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20210305_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisewithdraw',
            name='payment_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DepositMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('payment_address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('payment_approved', models.BooleanField(default=False)),
                ('payment_pending', models.BooleanField(default=False)),
                ('payment_rejected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
