# Generated by Django 3.0 on 2021-03-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20210306_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('national_id_front_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('national_id_back_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('driver_license_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pending', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
