# Generated by Django 3.0 on 2021-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_daily_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_refer_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
