# Generated by Django 3.0 on 2021-03-24 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_monthly_royality_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_royality_last_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
